// Code generated by protoc-gen-go.
// source: proto/wire/action.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	proto/wire/action.proto
	proto/wire/event.proto

It has these top-level messages:
	ActionEnvelope
	ActionGameLeave
	ActionGameLaunch
	EventEnvelope
	EventGameStart
	EventGameOver
	EventGameTick
*/
package wire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ActionEnvelope struct {
	// Types that are valid to be assigned to Action:
	//	*ActionEnvelope_ActionGameLeave
	//	*ActionEnvelope_ActionGameLaunch
	Action isActionEnvelope_Action `protobuf_oneof:"action"`
}

func (m *ActionEnvelope) Reset()                    { *m = ActionEnvelope{} }
func (m *ActionEnvelope) String() string            { return proto.CompactTextString(m) }
func (*ActionEnvelope) ProtoMessage()               {}
func (*ActionEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isActionEnvelope_Action interface {
	isActionEnvelope_Action()
}

type ActionEnvelope_ActionGameLeave struct {
	ActionGameLeave *ActionGameLeave `protobuf:"bytes,1,opt,name=action_game_leave,json=actionGameLeave,oneof"`
}
type ActionEnvelope_ActionGameLaunch struct {
	ActionGameLaunch *ActionGameLaunch `protobuf:"bytes,2,opt,name=action_game_launch,json=actionGameLaunch,oneof"`
}

func (*ActionEnvelope_ActionGameLeave) isActionEnvelope_Action()  {}
func (*ActionEnvelope_ActionGameLaunch) isActionEnvelope_Action() {}

func (m *ActionEnvelope) GetAction() isActionEnvelope_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ActionEnvelope) GetActionGameLeave() *ActionGameLeave {
	if x, ok := m.GetAction().(*ActionEnvelope_ActionGameLeave); ok {
		return x.ActionGameLeave
	}
	return nil
}

func (m *ActionEnvelope) GetActionGameLaunch() *ActionGameLaunch {
	if x, ok := m.GetAction().(*ActionEnvelope_ActionGameLaunch); ok {
		return x.ActionGameLaunch
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ActionEnvelope) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ActionEnvelope_OneofMarshaler, _ActionEnvelope_OneofUnmarshaler, _ActionEnvelope_OneofSizer, []interface{}{
		(*ActionEnvelope_ActionGameLeave)(nil),
		(*ActionEnvelope_ActionGameLaunch)(nil),
	}
}

func _ActionEnvelope_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ActionEnvelope)
	// action
	switch x := m.Action.(type) {
	case *ActionEnvelope_ActionGameLeave:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ActionGameLeave); err != nil {
			return err
		}
	case *ActionEnvelope_ActionGameLaunch:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ActionGameLaunch); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ActionEnvelope.Action has unexpected type %T", x)
	}
	return nil
}

func _ActionEnvelope_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ActionEnvelope)
	switch tag {
	case 1: // action.action_game_leave
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ActionGameLeave)
		err := b.DecodeMessage(msg)
		m.Action = &ActionEnvelope_ActionGameLeave{msg}
		return true, err
	case 2: // action.action_game_launch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ActionGameLaunch)
		err := b.DecodeMessage(msg)
		m.Action = &ActionEnvelope_ActionGameLaunch{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ActionEnvelope_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ActionEnvelope)
	// action
	switch x := m.Action.(type) {
	case *ActionEnvelope_ActionGameLeave:
		s := proto.Size(x.ActionGameLeave)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionEnvelope_ActionGameLaunch:
		s := proto.Size(x.ActionGameLaunch)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ActionGameLeave struct {
}

func (m *ActionGameLeave) Reset()                    { *m = ActionGameLeave{} }
func (m *ActionGameLeave) String() string            { return proto.CompactTextString(m) }
func (*ActionGameLeave) ProtoMessage()               {}
func (*ActionGameLeave) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ActionGameLaunch struct {
	IslandIdFrom string `protobuf:"bytes,1,opt,name=island_id_from,json=islandIdFrom" json:"island_id_from,omitempty"`
	IslandIdTo   string `protobuf:"bytes,2,opt,name=island_id_to,json=islandIdTo" json:"island_id_to,omitempty"`
}

func (m *ActionGameLaunch) Reset()                    { *m = ActionGameLaunch{} }
func (m *ActionGameLaunch) String() string            { return proto.CompactTextString(m) }
func (*ActionGameLaunch) ProtoMessage()               {}
func (*ActionGameLaunch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ActionGameLaunch) GetIslandIdFrom() string {
	if m != nil {
		return m.IslandIdFrom
	}
	return ""
}

func (m *ActionGameLaunch) GetIslandIdTo() string {
	if m != nil {
		return m.IslandIdTo
	}
	return ""
}

func init() {
	proto.RegisterType((*ActionEnvelope)(nil), "wire.ActionEnvelope")
	proto.RegisterType((*ActionGameLeave)(nil), "wire.ActionGameLeave")
	proto.RegisterType((*ActionGameLaunch)(nil), "wire.ActionGameLaunch")
}

func init() { proto.RegisterFile("proto/wire/action.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xcf, 0x2c, 0x4a, 0xd5, 0x4f, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x8b,
	0x08, 0xb1, 0x80, 0x84, 0x94, 0x96, 0x33, 0x72, 0xf1, 0x39, 0x82, 0x85, 0x5d, 0xf3, 0xca, 0x52,
	0x73, 0xf2, 0x0b, 0x52, 0x85, 0x9c, 0xb9, 0x04, 0x21, 0x0a, 0xe3, 0xd3, 0x13, 0x73, 0x53, 0xe3,
	0x73, 0x52, 0x13, 0xcb, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0x40, 0x9a,
	0xf4, 0x20, 0x1a, 0xdc, 0x13, 0x73, 0x53, 0x7d, 0x40, 0x92, 0x1e, 0x0c, 0x41, 0xfc, 0x89, 0xa8,
	0x42, 0x42, 0x6e, 0x5c, 0x42, 0x28, 0x86, 0x24, 0x96, 0xe6, 0x25, 0x67, 0x48, 0x30, 0x81, 0x4d,
	0x11, 0xc3, 0x30, 0x05, 0x2c, 0xeb, 0xc1, 0x10, 0x24, 0x90, 0x88, 0x26, 0xe6, 0xc4, 0xc1, 0xc5,
	0x06, 0x11, 0x53, 0x12, 0xe4, 0xe2, 0x47, 0xb3, 0x57, 0x29, 0x8a, 0x4b, 0x00, 0xdd, 0x10, 0x21,
	0x15, 0x2e, 0xbe, 0xcc, 0xe2, 0x9c, 0xc4, 0xbc, 0x94, 0xf8, 0xcc, 0x94, 0xf8, 0xb4, 0xa2, 0xfc,
	0x5c, 0xb0, 0xd3, 0x39, 0x83, 0x78, 0x20, 0xa2, 0x9e, 0x29, 0x6e, 0x45, 0xf9, 0xb9, 0x42, 0x0a,
	0x5c, 0x3c, 0x08, 0x55, 0x25, 0xf9, 0x60, 0x87, 0x71, 0x06, 0x71, 0xc1, 0xd4, 0x84, 0xe4, 0x3b,
	0x71, 0x45, 0x71, 0xe4, 0x64, 0x26, 0x81, 0xc3, 0x2d, 0x89, 0x0d, 0x1c, 0x62, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb4, 0xbb, 0xdc, 0xb5, 0x4c, 0x01, 0x00, 0x00,
}
