// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wire/action.proto

package wire // import "github.com/verath/archipelago/lib/wire"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ActionEnvelope struct {
	// Types that are valid to be assigned to Action:
	//	*ActionEnvelope_ActionGameLeave
	//	*ActionEnvelope_ActionGameLaunch
	Action               isActionEnvelope_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ActionEnvelope) Reset()         { *m = ActionEnvelope{} }
func (m *ActionEnvelope) String() string { return proto.CompactTextString(m) }
func (*ActionEnvelope) ProtoMessage()    {}
func (*ActionEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_eb8d68e132499597, []int{0}
}
func (m *ActionEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionEnvelope.Unmarshal(m, b)
}
func (m *ActionEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionEnvelope.Marshal(b, m, deterministic)
}
func (dst *ActionEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionEnvelope.Merge(dst, src)
}
func (m *ActionEnvelope) XXX_Size() int {
	return xxx_messageInfo_ActionEnvelope.Size(m)
}
func (m *ActionEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ActionEnvelope proto.InternalMessageInfo

type isActionEnvelope_Action interface {
	isActionEnvelope_Action()
}

type ActionEnvelope_ActionGameLeave struct {
	ActionGameLeave *ActionGameLeave `protobuf:"bytes,1,opt,name=action_game_leave,json=actionGameLeave,proto3,oneof"`
}
type ActionEnvelope_ActionGameLaunch struct {
	ActionGameLaunch *ActionGameLaunch `protobuf:"bytes,2,opt,name=action_game_launch,json=actionGameLaunch,proto3,oneof"`
}

func (*ActionEnvelope_ActionGameLeave) isActionEnvelope_Action()  {}
func (*ActionEnvelope_ActionGameLaunch) isActionEnvelope_Action() {}

func (m *ActionEnvelope) GetAction() isActionEnvelope_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ActionEnvelope) GetActionGameLeave() *ActionGameLeave {
	if x, ok := m.GetAction().(*ActionEnvelope_ActionGameLeave); ok {
		return x.ActionGameLeave
	}
	return nil
}

func (m *ActionEnvelope) GetActionGameLaunch() *ActionGameLaunch {
	if x, ok := m.GetAction().(*ActionEnvelope_ActionGameLaunch); ok {
		return x.ActionGameLaunch
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ActionEnvelope) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ActionEnvelope_OneofMarshaler, _ActionEnvelope_OneofUnmarshaler, _ActionEnvelope_OneofSizer, []interface{}{
		(*ActionEnvelope_ActionGameLeave)(nil),
		(*ActionEnvelope_ActionGameLaunch)(nil),
	}
}

func _ActionEnvelope_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ActionEnvelope)
	// action
	switch x := m.Action.(type) {
	case *ActionEnvelope_ActionGameLeave:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ActionGameLeave); err != nil {
			return err
		}
	case *ActionEnvelope_ActionGameLaunch:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ActionGameLaunch); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ActionEnvelope.Action has unexpected type %T", x)
	}
	return nil
}

func _ActionEnvelope_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ActionEnvelope)
	switch tag {
	case 1: // action.action_game_leave
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ActionGameLeave)
		err := b.DecodeMessage(msg)
		m.Action = &ActionEnvelope_ActionGameLeave{msg}
		return true, err
	case 2: // action.action_game_launch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ActionGameLaunch)
		err := b.DecodeMessage(msg)
		m.Action = &ActionEnvelope_ActionGameLaunch{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ActionEnvelope_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ActionEnvelope)
	// action
	switch x := m.Action.(type) {
	case *ActionEnvelope_ActionGameLeave:
		s := proto.Size(x.ActionGameLeave)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ActionEnvelope_ActionGameLaunch:
		s := proto.Size(x.ActionGameLaunch)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ActionGameLeave struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionGameLeave) Reset()         { *m = ActionGameLeave{} }
func (m *ActionGameLeave) String() string { return proto.CompactTextString(m) }
func (*ActionGameLeave) ProtoMessage()    {}
func (*ActionGameLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_eb8d68e132499597, []int{1}
}
func (m *ActionGameLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionGameLeave.Unmarshal(m, b)
}
func (m *ActionGameLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionGameLeave.Marshal(b, m, deterministic)
}
func (dst *ActionGameLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionGameLeave.Merge(dst, src)
}
func (m *ActionGameLeave) XXX_Size() int {
	return xxx_messageInfo_ActionGameLeave.Size(m)
}
func (m *ActionGameLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionGameLeave.DiscardUnknown(m)
}

var xxx_messageInfo_ActionGameLeave proto.InternalMessageInfo

type ActionGameLaunch struct {
	FromId               string   `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId                 string   `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionGameLaunch) Reset()         { *m = ActionGameLaunch{} }
func (m *ActionGameLaunch) String() string { return proto.CompactTextString(m) }
func (*ActionGameLaunch) ProtoMessage()    {}
func (*ActionGameLaunch) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_eb8d68e132499597, []int{2}
}
func (m *ActionGameLaunch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionGameLaunch.Unmarshal(m, b)
}
func (m *ActionGameLaunch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionGameLaunch.Marshal(b, m, deterministic)
}
func (dst *ActionGameLaunch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionGameLaunch.Merge(dst, src)
}
func (m *ActionGameLaunch) XXX_Size() int {
	return xxx_messageInfo_ActionGameLaunch.Size(m)
}
func (m *ActionGameLaunch) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionGameLaunch.DiscardUnknown(m)
}

var xxx_messageInfo_ActionGameLaunch proto.InternalMessageInfo

func (m *ActionGameLaunch) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *ActionGameLaunch) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func init() {
	proto.RegisterType((*ActionEnvelope)(nil), "wire.ActionEnvelope")
	proto.RegisterType((*ActionGameLeave)(nil), "wire.ActionGameLeave")
	proto.RegisterType((*ActionGameLaunch)(nil), "wire.ActionGameLaunch")
}

func init() { proto.RegisterFile("wire/action.proto", fileDescriptor_action_eb8d68e132499597) }

var fileDescriptor_action_eb8d68e132499597 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0x9b, 0xaa, 0x04, 0x78, 0x48, 0xb4, 0x31, 0x02, 0x3a, 0xa2, 0x0c, 0xa8, 0x53, 0x2c,
	0xc1, 0x0f, 0x40, 0x11, 0xd0, 0x4a, 0x4c, 0x19, 0x59, 0xa2, 0x97, 0xe4, 0x91, 0x58, 0xb2, 0xf3,
	0x22, 0xcb, 0x0d, 0x9f, 0xc4, 0x6f, 0x22, 0x3b, 0x53, 0xd3, 0xd1, 0xe7, 0xfa, 0x1e, 0x5f, 0x19,
	0x92, 0x5f, 0x65, 0x49, 0x62, 0xe5, 0x14, 0x77, 0x59, 0x6f, 0xd9, 0xb1, 0x58, 0x78, 0x94, 0xfe,
	0x45, 0x70, 0xfd, 0x1a, 0xf0, 0x7b, 0x37, 0x90, 0xe6, 0x9e, 0xc4, 0x1b, 0x24, 0xe3, 0xc5, 0xa2,
	0x41, 0x43, 0x85, 0x26, 0x1c, 0x68, 0x1d, 0x3d, 0x44, 0x9b, 0xab, 0xa7, 0xdb, 0xcc, 0x97, 0xb2,
	0xb1, 0xf0, 0x89, 0x86, 0xbe, 0x7c, 0xb8, 0x9b, 0xe5, 0x4b, 0x3c, 0x46, 0xe2, 0x03, 0xc4, 0x91,
	0x04, 0x0f, 0x5d, 0xd5, 0xae, 0xe7, 0xc1, 0x72, 0x77, 0x62, 0x09, 0xe9, 0x6e, 0x96, 0xaf, 0x70,
	0xc2, 0xb6, 0x17, 0x10, 0x8f, 0x2c, 0x4d, 0x60, 0x39, 0x79, 0x37, 0x7d, 0x81, 0xd5, 0x54, 0x22,
	0xee, 0xe1, 0xfc, 0xc7, 0xb2, 0x29, 0x54, 0x1d, 0x36, 0x5f, 0xe6, 0xb1, 0x3f, 0xee, 0x6b, 0x71,
	0x03, 0x67, 0x8e, 0x3d, 0x9e, 0x07, 0xbc, 0x70, 0xbc, 0xaf, 0xb7, 0x9b, 0xef, 0xc7, 0x46, 0xb9,
	0xf6, 0x50, 0x66, 0x15, 0x1b, 0x39, 0x90, 0x45, 0xd7, 0x4a, 0xb4, 0x55, 0xab, 0x7a, 0xd2, 0xd8,
	0xb0, 0xd4, 0xaa, 0x94, 0x7e, 0x6d, 0x19, 0x87, 0x5f, 0x7b, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xbf, 0xb5, 0x25, 0xfa, 0x4a, 0x01, 0x00, 0x00,
}
