// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wire/event.proto

package wire

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	game "github.com/verath/archipelago/lib/wire/game"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventEnvelope struct {
	// Types that are valid to be assigned to Event:
	//	*EventEnvelope_EventGameStart
	//	*EventEnvelope_EventGameOver
	//	*EventEnvelope_EventGameTick
	Event                isEventEnvelope_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventEnvelope) Reset()         { *m = EventEnvelope{} }
func (m *EventEnvelope) String() string { return proto.CompactTextString(m) }
func (*EventEnvelope) ProtoMessage()    {}
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_53453297b62384fb, []int{0}
}

func (m *EventEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventEnvelope.Unmarshal(m, b)
}
func (m *EventEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventEnvelope.Marshal(b, m, deterministic)
}
func (m *EventEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventEnvelope.Merge(m, src)
}
func (m *EventEnvelope) XXX_Size() int {
	return xxx_messageInfo_EventEnvelope.Size(m)
}
func (m *EventEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_EventEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_EventEnvelope proto.InternalMessageInfo

type isEventEnvelope_Event interface {
	isEventEnvelope_Event()
}

type EventEnvelope_EventGameStart struct {
	EventGameStart *EventGameStart `protobuf:"bytes,1,opt,name=event_game_start,json=eventGameStart,proto3,oneof"`
}

type EventEnvelope_EventGameOver struct {
	EventGameOver *EventGameOver `protobuf:"bytes,2,opt,name=event_game_over,json=eventGameOver,proto3,oneof"`
}

type EventEnvelope_EventGameTick struct {
	EventGameTick *EventGameTick `protobuf:"bytes,3,opt,name=event_game_tick,json=eventGameTick,proto3,oneof"`
}

func (*EventEnvelope_EventGameStart) isEventEnvelope_Event() {}

func (*EventEnvelope_EventGameOver) isEventEnvelope_Event() {}

func (*EventEnvelope_EventGameTick) isEventEnvelope_Event() {}

func (m *EventEnvelope) GetEvent() isEventEnvelope_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *EventEnvelope) GetEventGameStart() *EventGameStart {
	if x, ok := m.GetEvent().(*EventEnvelope_EventGameStart); ok {
		return x.EventGameStart
	}
	return nil
}

func (m *EventEnvelope) GetEventGameOver() *EventGameOver {
	if x, ok := m.GetEvent().(*EventEnvelope_EventGameOver); ok {
		return x.EventGameOver
	}
	return nil
}

func (m *EventEnvelope) GetEventGameTick() *EventGameTick {
	if x, ok := m.GetEvent().(*EventEnvelope_EventGameTick); ok {
		return x.EventGameTick
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventEnvelope) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventEnvelope_EventGameStart)(nil),
		(*EventEnvelope_EventGameOver)(nil),
		(*EventEnvelope_EventGameTick)(nil),
	}
}

type EventGameStart struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TickInterval         int64    `protobuf:"varint,2,opt,name=tick_interval,json=tickInterval,proto3" json:"tick_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventGameStart) Reset()         { *m = EventGameStart{} }
func (m *EventGameStart) String() string { return proto.CompactTextString(m) }
func (*EventGameStart) ProtoMessage()    {}
func (*EventGameStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_53453297b62384fb, []int{1}
}

func (m *EventGameStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGameStart.Unmarshal(m, b)
}
func (m *EventGameStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGameStart.Marshal(b, m, deterministic)
}
func (m *EventGameStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGameStart.Merge(m, src)
}
func (m *EventGameStart) XXX_Size() int {
	return xxx_messageInfo_EventGameStart.Size(m)
}
func (m *EventGameStart) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGameStart.DiscardUnknown(m)
}

var xxx_messageInfo_EventGameStart proto.InternalMessageInfo

func (m *EventGameStart) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *EventGameStart) GetTickInterval() int64 {
	if m != nil {
		return m.TickInterval
	}
	return 0
}

type EventGameOver struct {
	WinnerId             string   `protobuf:"bytes,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventGameOver) Reset()         { *m = EventGameOver{} }
func (m *EventGameOver) String() string { return proto.CompactTextString(m) }
func (*EventGameOver) ProtoMessage()    {}
func (*EventGameOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_53453297b62384fb, []int{2}
}

func (m *EventGameOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGameOver.Unmarshal(m, b)
}
func (m *EventGameOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGameOver.Marshal(b, m, deterministic)
}
func (m *EventGameOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGameOver.Merge(m, src)
}
func (m *EventGameOver) XXX_Size() int {
	return xxx_messageInfo_EventGameOver.Size(m)
}
func (m *EventGameOver) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGameOver.DiscardUnknown(m)
}

var xxx_messageInfo_EventGameOver proto.InternalMessageInfo

func (m *EventGameOver) GetWinnerId() string {
	if m != nil {
		return m.WinnerId
	}
	return ""
}

type EventGameTick struct {
	Game                 *game.Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EventGameTick) Reset()         { *m = EventGameTick{} }
func (m *EventGameTick) String() string { return proto.CompactTextString(m) }
func (*EventGameTick) ProtoMessage()    {}
func (*EventGameTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_53453297b62384fb, []int{3}
}

func (m *EventGameTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGameTick.Unmarshal(m, b)
}
func (m *EventGameTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGameTick.Marshal(b, m, deterministic)
}
func (m *EventGameTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGameTick.Merge(m, src)
}
func (m *EventGameTick) XXX_Size() int {
	return xxx_messageInfo_EventGameTick.Size(m)
}
func (m *EventGameTick) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGameTick.DiscardUnknown(m)
}

var xxx_messageInfo_EventGameTick proto.InternalMessageInfo

func (m *EventGameTick) GetGame() *game.Game {
	if m != nil {
		return m.Game
	}
	return nil
}

func init() {
	proto.RegisterType((*EventEnvelope)(nil), "wire.EventEnvelope")
	proto.RegisterType((*EventGameStart)(nil), "wire.EventGameStart")
	proto.RegisterType((*EventGameOver)(nil), "wire.EventGameOver")
	proto.RegisterType((*EventGameTick)(nil), "wire.EventGameTick")
}

func init() { proto.RegisterFile("wire/event.proto", fileDescriptor_53453297b62384fb) }

var fileDescriptor_53453297b62384fb = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdf, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xb7, 0xef, 0xf6, 0x55, 0x17, 0xdd, 0x0f, 0xa2, 0xc2, 0x70, 0x2f, 0xd2, 0x81, 0xec,
	0x41, 0x1a, 0x50, 0x5f, 0x05, 0x19, 0x0c, 0xb7, 0x27, 0x21, 0xfa, 0xe4, 0x4b, 0xc9, 0xda, 0x4b,
	0x1b, 0x96, 0x36, 0x25, 0xc6, 0x0c, 0xff, 0x53, 0xff, 0x1c, 0xb9, 0x69, 0x91, 0x76, 0xf8, 0xfa,
	0xb9, 0xe7, 0x9c, 0x9c, 0x7b, 0x43, 0x26, 0x7b, 0x69, 0x80, 0x81, 0x83, 0xc2, 0x86, 0xa5, 0xd1,
	0x56, 0xd3, 0x3e, 0x92, 0xab, 0x4b, 0xcf, 0x53, 0x91, 0x03, 0xcb, 0x75, 0x02, 0xaa, 0x1a, 0x06,
	0xdf, 0x5d, 0x32, 0x5c, 0xa1, 0x78, 0x55, 0x38, 0x50, 0xba, 0x04, 0xfa, 0x44, 0x26, 0xde, 0x1d,
	0xa1, 0x36, 0xfa, 0xb0, 0xc2, 0xd8, 0x69, 0xf7, 0xba, 0xbb, 0x38, 0xbd, 0xbb, 0x08, 0x31, 0x23,
	0xf4, 0xf2, 0x67, 0x91, 0xc3, 0x2b, 0xce, 0xd6, 0x1d, 0x3e, 0x82, 0x16, 0xa1, 0x8f, 0x64, 0xdc,
	0x48, 0xd0, 0x0e, 0xcc, 0xf4, 0x9f, 0x0f, 0x38, 0x3f, 0x08, 0x78, 0x71, 0x60, 0xd6, 0x1d, 0x3e,
	0x84, 0x26, 0x38, 0xb0, 0x5b, 0x19, 0xef, 0xa6, 0xbd, 0x3f, 0xed, 0x6f, 0x32, 0xde, 0xb5, 0xec,
	0x08, 0x96, 0xc7, 0xe4, 0xbf, 0x07, 0x01, 0x27, 0xa3, 0x76, 0x55, 0x3a, 0x23, 0x83, 0x52, 0x89,
	0x2f, 0x30, 0x91, 0x4c, 0xfc, 0x4e, 0x03, 0x7e, 0x52, 0x81, 0x4d, 0x42, 0xe7, 0x64, 0x88, 0x6f,
	0x45, 0xb2, 0xb0, 0x60, 0x9c, 0x50, 0xbe, 0x73, 0x8f, 0x9f, 0x21, 0xdc, 0xd4, 0x2c, 0xb8, 0xad,
	0xaf, 0xf5, 0x5b, 0x76, 0x46, 0x06, 0x7b, 0x59, 0x14, 0xad, 0xc8, 0x0a, 0x6c, 0x92, 0xe0, 0xa1,
	0xa1, 0xc6, 0x6e, 0x74, 0x4e, 0xfa, 0xb8, 0x54, 0x7d, 0xcf, 0x71, 0xb5, 0x0f, 0x92, 0x10, 0x25,
	0xdc, 0x0f, 0x97, 0x8b, 0xf7, 0x9b, 0x54, 0xda, 0xec, 0x73, 0x1b, 0xc6, 0x3a, 0x67, 0x0e, 0x8c,
	0xb0, 0x19, 0x13, 0x26, 0xce, 0x64, 0x09, 0x4a, 0xa4, 0x9a, 0x29, 0xb9, 0x65, 0xe8, 0xdc, 0x1e,
	0xf9, 0x3f, 0xbc, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x19, 0x1c, 0x5a, 0x52, 0xf4, 0x01, 0x00,
	0x00,
}
