engines:
  fixme:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - "**.go"
    - "**.js"
    - "**.css"

exclude_paths:
  - config/
  - vendor/