engines:
  fixme:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
    config:
      config: web/.eslintrc.json
  fixme:
    enabled: true

ratings:
  paths:
    - "**.go"
    - "**.js"
    - "**.css"

exclude_paths:
  - config/
  - vendor/
  - "**pb.go"
  - "**proto_bundle.js"
  - "**proto_bundle.d.ts"
