# Dockerfile for building the frontend part of Archipelago
# docker build -t verath/archipelago-dev-frontend -f Dockerfile.dev-frontend .

FROM circleci/node:6

# Python3, pip from Debian package manager
RUN sudo apt-get -y update && \
	sudo apt-get install -y --no-install-recommends \
		python3-dev \
		python3-pip \
	&& \
	sudo apt-get clean && \
	sudo rm -rf /var/lib/apt/lists/*

# Make sure we are running an updated pip
RUN sudo pip3 install -U pip

# Install the AWS CLI
RUN pip3 install awscli --upgrade --user
