
version: 2
jobs:
  build_backend:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/verath/archipelago
    steps:
      - checkout
      - run: go build -v
      - run: go test -v -race -timeout 30s ./...

  build_frontend:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-frontend-yarn-{{ checksum "web/yarn.lock" }}
      - run: cd web && yarn install
      - run: cd web && yarn run lint
      - run: cd web && yarn run build:prod -- --display-error-details --devtool source-map
      - save_cache:
          key: v1-frontend-yarn-{{ checksum "web/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - web/dist

  docker_publish:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push backend docker image
          command: |
            docker build --pull -t verath/archipelago-backend:master .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push verath/archipelago-backend:master

workflows:
  version: 2
  build_frontend_backend:
    jobs:
      - build_backend
      - build_frontend
      - docker_publish:
          requires:
            - build_backend
          filters:
            branches:
              only: master
