
version: 2
jobs:
  build_backend:
    docker:
      - image: golang:1.10
    working_directory: /go/src/github.com/verath/archipelago
    steps:
      - checkout
      - run: go build -v
      - run: go test -v -race -timeout 30s ./...

  build_frontend:
    docker:
      - image: node:8.11
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v2-frontend-yarn-{{ checksum "web/yarn.lock" }}
            - v2-frontend-yarn-
      - run: cd web && yarn install
      - run: cd web && yarn run lint
      - run: cd web && yarn run build:prod -- --display-error-details --devtool source-map
      - save_cache:
          key: v2-frontend-yarn-{{ checksum "web/yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - web/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - web/dist

  docker_publish_backend:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push backend docker image
          command: |
            docker build --pull -t verath/archipelago-backend:master .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push verath/archipelago-backend:master

  deploy:
    docker:
      - image: node:8.11
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-frontend-yarn-{{ checksum "web/yarn.lock" }}
            - v2-frontend-yarn-
      - attach_workspace:
          at: ~/project
      - run:
          name: "Setup deploy prerequisites"
          command: |
            # yarn install to get the firebase cli
            cd web && yarn install
            # Add our server remote public key to known_hosts
            mkdir -p ~/.ssh
            echo 'ws.playarchipelago.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDazWfFxpfso8v7tzh9jr0HnInPcg2GyiVP5LP/ErjVirsftf+1gk4D9RVsYvv+cjt571FvlgYJCBgOnoYXaz6Ud+qzcutE3y9s6AoeRvQXwrrhj1bUlNUTxhn1ywDQ6C68wnWjK3u0uH2PsdHybfNhSe64Mc/EuqAAxa4rwFNEEgjBbL2dT0y750tFDMsZFLRK9Mt74cmRTQbzYrbf1HBM8XHVHtC13vvd5Yi3IK85fZpSRklz4Fb08GUgQLcx+qjFsR3FNKFgHxa2ub0UWWedH1qLB3ku4NR85eP3+vtOrbxOg2tr5seiINiGed3h5y62At2YnCEnqGl2eCWnIKPB' > ~/.ssh/known_hosts
      - deploy:
          name: Deploy frontend to firebase
          working_directory: ~/project/web
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
      - deploy:
          name: Deploy backend to ws.playarchipelago.com
          command: ssh circleci@ws.playarchipelago.com "./update_archipelago.sh"

workflows:
  version: 2
  build_frontend_backend:
    jobs:
      - build_backend
      - build_frontend
      - docker_publish_backend:
          requires:
            - build_backend
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_frontend
            - build_backend
            - docker_publish_backend
          filters:
            branches:
              only: master
