
version: 2
jobs:
  build_backend:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/verath/archipelago
    steps:
      - checkout
      - run: go test -v -race -timeout 30s ./...
  build_frontend:
    docker:
        - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-frontend-yarn-{{ checksum "web/yarn.lock" }}
      # Install python and the aws cli:
      - run:
          name: Install awscli
          working_directory: /tmp
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3
            python3 --version
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3 get-pip.py --user
            pip install awscli --upgrade --user
            aws --version
      # Install frontend deps, lint and build
      - run: cd web && yarn install
      - run: cd web && yarn run lint
      - run: cd web && yarn run build:prod -- --display-error-details --devtool source-map
      - save_cache:
          key: v1-frontend-yarn-{{ checksum "web/yarn.lock" }}
          paths: 
            - ~/.cache/yarn
      # Deploy the built files to our S3 bucket
      - deploy:
          name: Deploy frontend to S3
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                aws s3 sync web/dist s3://archipelago-frontend --delete
              else
                echo "Not master branch so not deploying"
              fi
workflows:
  version: 2
  build_frontend_backend:
    jobs:
      - build_backend
      - build_frontend:
          requires:
            - build_backend
