
version: 2
jobs:
  build_test_backend:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/verath/archipelago
    steps:
      - checkout
      - run: go test -v -race -timeout 30s ./...
  build_frontend:
    docker:
        - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-frontend-yarn-{{ checksum "web/yarn.lock" }}
      - run: cd web && yarn install
      - run: cd web && yarn run lint
      - run: cd web && yarn run build:prod
      - save_cache:
          key: v1-frontend-yarn-{{ checksum "web/yarn.lock" }}
          paths: 
            - ~/.cache/yarn
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test_backend
      - build_frontend
