
version: 2
jobs:
  build_test_backend:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/verath/archipelago
    steps:
      - checkout
      - run: go test -v -race -timeout 30s ./...
  build_frontend:
    docker:
        - image: circleci/node:6
    steps:
      - checkout
      - run: cd web && yarn install
      - run: cd web && yarn build:prod
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test_backend
      - build_frontend
