// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wire/game/model.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coordinate struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_58314dfb3cd76f5b, []int{0}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinate) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type FloatCoordinate struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FloatCoordinate) Reset()         { *m = FloatCoordinate{} }
func (m *FloatCoordinate) String() string { return proto.CompactTextString(m) }
func (*FloatCoordinate) ProtoMessage()    {}
func (*FloatCoordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_58314dfb3cd76f5b, []int{1}
}

func (m *FloatCoordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatCoordinate.Unmarshal(m, b)
}
func (m *FloatCoordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatCoordinate.Marshal(b, m, deterministic)
}
func (m *FloatCoordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatCoordinate.Merge(m, src)
}
func (m *FloatCoordinate) XXX_Size() int {
	return xxx_messageInfo_FloatCoordinate.Size(m)
}
func (m *FloatCoordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatCoordinate.DiscardUnknown(m)
}

var xxx_messageInfo_FloatCoordinate proto.InternalMessageInfo

func (m *FloatCoordinate) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *FloatCoordinate) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Player struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Coordinates where fog of war is present.
	FogOfWar             []*Coordinate `protobuf:"bytes,7,rep,name=fog_of_war,json=fogOfWar,proto3" json:"fog_of_war,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_58314dfb3cd76f5b, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetFogOfWar() []*Coordinate {
	if m != nil {
		return m.FogOfWar
	}
	return nil
}

type Army struct {
	OwnerId              string   `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Strength             int64    `protobuf:"varint,2,opt,name=strength,proto3" json:"strength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Army) Reset()         { *m = Army{} }
func (m *Army) String() string { return proto.CompactTextString(m) }
func (*Army) ProtoMessage()    {}
func (*Army) Descriptor() ([]byte, []int) {
	return fileDescriptor_58314dfb3cd76f5b, []int{3}
}

func (m *Army) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Army.Unmarshal(m, b)
}
func (m *Army) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Army.Marshal(b, m, deterministic)
}
func (m *Army) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Army.Merge(m, src)
}
func (m *Army) XXX_Size() int {
	return xxx_messageInfo_Army.Size(m)
}
func (m *Army) XXX_DiscardUnknown() {
	xxx_messageInfo_Army.DiscardUnknown(m)
}

var xxx_messageInfo_Army proto.InternalMessageInfo

func (m *Army) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Army) GetStrength() int64 {
	if m != nil {
		return m.Strength
	}
	return 0
}

type Airplane struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Army                 *Army            `protobuf:"bytes,2,opt,name=army,proto3" json:"army,omitempty"`
	Position             *FloatCoordinate `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Direction            float64          `protobuf:"fixed64,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                float64          `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Airplane) Reset()         { *m = Airplane{} }
func (m *Airplane) String() string { return proto.CompactTextString(m) }
func (*Airplane) ProtoMessage()    {}
func (*Airplane) Descriptor() ([]byte, []int) {
	return fileDescriptor_58314dfb3cd76f5b, []int{4}
}

func (m *Airplane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Airplane.Unmarshal(m, b)
}
func (m *Airplane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Airplane.Marshal(b, m, deterministic)
}
func (m *Airplane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Airplane.Merge(m, src)
}
func (m *Airplane) XXX_Size() int {
	return xxx_messageInfo_Airplane.Size(m)
}
func (m *Airplane) XXX_DiscardUnknown() {
	xxx_messageInfo_Airplane.DiscardUnknown(m)
}

var xxx_messageInfo_Airplane proto.InternalMessageInfo

func (m *Airplane) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Airplane) GetArmy() *Army {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *Airplane) GetPosition() *FloatCoordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Airplane) GetDirection() float64 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Airplane) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Island struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Army                 *Army       `protobuf:"bytes,2,opt,name=army,proto3" json:"army,omitempty"`
	Position             *Coordinate `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Size                 float64     `protobuf:"fixed64,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Island) Reset()         { *m = Island{} }
func (m *Island) String() string { return proto.CompactTextString(m) }
func (*Island) ProtoMessage()    {}
func (*Island) Descriptor() ([]byte, []int) {
	return fileDescriptor_58314dfb3cd76f5b, []int{5}
}

func (m *Island) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Island.Unmarshal(m, b)
}
func (m *Island) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Island.Marshal(b, m, deterministic)
}
func (m *Island) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Island.Merge(m, src)
}
func (m *Island) XXX_Size() int {
	return xxx_messageInfo_Island.Size(m)
}
func (m *Island) XXX_DiscardUnknown() {
	xxx_messageInfo_Island.DiscardUnknown(m)
}

var xxx_messageInfo_Island proto.InternalMessageInfo

func (m *Island) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Island) GetArmy() *Army {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *Island) GetPosition() *Coordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Island) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Game struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 *Coordinate `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	PlayerNeutral        *Player     `protobuf:"bytes,3,opt,name=player_neutral,json=playerNeutral,proto3" json:"player_neutral,omitempty"`
	Players              []*Player   `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	Islands              []*Island   `protobuf:"bytes,5,rep,name=islands,proto3" json:"islands,omitempty"`
	Airplanes            []*Airplane `protobuf:"bytes,6,rep,name=airplanes,proto3" json:"airplanes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_58314dfb3cd76f5b, []int{6}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Game) GetSize() *Coordinate {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Game) GetPlayerNeutral() *Player {
	if m != nil {
		return m.PlayerNeutral
	}
	return nil
}

func (m *Game) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Game) GetIslands() []*Island {
	if m != nil {
		return m.Islands
	}
	return nil
}

func (m *Game) GetAirplanes() []*Airplane {
	if m != nil {
		return m.Airplanes
	}
	return nil
}

func init() {
	proto.RegisterType((*Coordinate)(nil), "wire.game.Coordinate")
	proto.RegisterType((*FloatCoordinate)(nil), "wire.game.FloatCoordinate")
	proto.RegisterType((*Player)(nil), "wire.game.Player")
	proto.RegisterType((*Army)(nil), "wire.game.Army")
	proto.RegisterType((*Airplane)(nil), "wire.game.Airplane")
	proto.RegisterType((*Island)(nil), "wire.game.Island")
	proto.RegisterType((*Game)(nil), "wire.game.Game")
}

func init() { proto.RegisterFile("wire/game/model.proto", fileDescriptor_58314dfb3cd76f5b) }

var fileDescriptor_58314dfb3cd76f5b = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xe5, 0x34, 0x6d, 0xd3, 0x37, 0xd8, 0x84, 0x61, 0x92, 0x99, 0x38, 0x4c, 0xe1, 0x52,
	0x34, 0x2d, 0xd1, 0x36, 0x09, 0x71, 0xe1, 0x30, 0x90, 0x40, 0x3b, 0xf0, 0x43, 0xbe, 0x20, 0x71,
	0xa9, 0xdc, 0xda, 0x4d, 0x2d, 0x39, 0x71, 0x64, 0x7b, 0x74, 0xe5, 0xcc, 0x81, 0xff, 0x85, 0x7f,
	0x12, 0xc5, 0xce, 0xd2, 0x42, 0x06, 0x87, 0xdd, 0xfc, 0x7d, 0xef, 0xf3, 0xec, 0xaf, 0xbe, 0x7a,
	0x86, 0xc3, 0xb5, 0x34, 0x22, 0x2f, 0x58, 0x29, 0xf2, 0x52, 0x73, 0xa1, 0xb2, 0xda, 0x68, 0xa7,
	0xf1, 0xa4, 0x29, 0x67, 0x4d, 0x39, 0x9d, 0x02, 0xbc, 0xd5, 0xda, 0x70, 0x59, 0x31, 0x27, 0xf0,
	0x03, 0x40, 0x37, 0x04, 0x1d, 0xa3, 0xe9, 0x80, 0xa2, 0x9b, 0x46, 0x6d, 0x48, 0x14, 0xd4, 0x26,
	0x3d, 0x85, 0x83, 0x77, 0x4a, 0x33, 0x77, 0x17, 0x8e, 0xfe, 0xc0, 0x51, 0x83, 0x7f, 0x80, 0xd1,
	0x67, 0xc5, 0x36, 0xc2, 0xe0, 0x7d, 0x88, 0x24, 0xf7, 0xd8, 0x84, 0x46, 0x92, 0xe3, 0x0b, 0x80,
	0xa5, 0x2e, 0x66, 0x7a, 0x39, 0x5b, 0x33, 0x43, 0xc6, 0xc7, 0x83, 0xe9, 0xde, 0xf9, 0x61, 0xd6,
	0x59, 0xca, 0xb6, 0x0f, 0xd0, 0x64, 0xa9, 0x8b, 0x4f, 0xcb, 0x2f, 0xcc, 0xa4, 0xaf, 0x21, 0xbe,
	0x34, 0xe5, 0x06, 0x3f, 0x85, 0x44, 0xaf, 0x2b, 0x61, 0x66, 0xdd, 0x95, 0x63, 0xaf, 0xaf, 0x38,
	0x3e, 0x82, 0xc4, 0x3a, 0x23, 0xaa, 0xc2, 0xad, 0x5a, 0xd7, 0x9d, 0x4e, 0x7f, 0x21, 0x48, 0x2e,
	0xa5, 0xa9, 0x15, 0xab, 0x44, 0xcf, 0xd0, 0x73, 0x88, 0x99, 0x29, 0x83, 0xf7, 0xbd, 0xf3, 0x83,
	0x1d, 0x2b, 0xcd, 0x93, 0xd4, 0x37, 0xf1, 0x4b, 0x48, 0x6a, 0x6d, 0xa5, 0x93, 0xba, 0x22, 0x03,
	0x0f, 0x1e, 0xed, 0x80, 0x7f, 0x25, 0x43, 0x3b, 0x16, 0x3f, 0x83, 0x09, 0x97, 0x46, 0x2c, 0xfc,
	0x60, 0xec, 0xd3, 0xd9, 0x16, 0xf0, 0x13, 0x18, 0xda, 0x5a, 0x08, 0x4e, 0x86, 0xbe, 0x13, 0x44,
	0xfa, 0x03, 0xc1, 0xe8, 0xca, 0x2a, 0x56, 0xf1, 0xfb, 0x79, 0x3d, 0xeb, 0x79, 0xfd, 0x57, 0xbe,
	0x9d, 0x4d, 0x0c, 0xb1, 0x95, 0xdf, 0x45, 0xeb, 0xd0, 0x9f, 0xd3, 0x9f, 0x11, 0xc4, 0xef, 0x59,
	0xd9, 0x0f, 0xec, 0x45, 0x0b, 0x47, 0xff, 0xbb, 0xdb, 0x23, 0xf8, 0x15, 0xec, 0xd7, 0x7e, 0x0d,
	0x66, 0x95, 0xb8, 0x76, 0x86, 0xa9, 0xd6, 0xd0, 0xa3, 0x9d, 0xa1, 0xb0, 0x27, 0xf4, 0x61, 0x00,
	0x3f, 0x06, 0x0e, 0x9f, 0xc0, 0x38, 0x14, 0x2c, 0x89, 0xfd, 0x8e, 0xdc, 0x31, 0x72, 0x4b, 0x34,
	0xb0, 0xf4, 0x81, 0x59, 0x32, 0xec, 0xc1, 0x21, 0x4a, 0x7a, 0x4b, 0xe0, 0x33, 0x98, 0xb0, 0x76,
	0x17, 0x2c, 0x19, 0x79, 0xfc, 0xf1, 0x6e, 0x90, 0x6d, 0x8f, 0x6e, 0xa9, 0x37, 0xa7, 0x5f, 0x4f,
	0x0a, 0xe9, 0x56, 0xd7, 0xf3, 0x6c, 0xa1, 0xcb, 0xfc, 0x9b, 0x30, 0xcc, 0xad, 0x72, 0x66, 0x16,
	0x2b, 0x59, 0x0b, 0xc5, 0x0a, 0x9d, 0x2b, 0x39, 0xcf, 0xbb, 0xcf, 0x36, 0x1f, 0xf9, 0x7f, 0x76,
	0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x78, 0x16, 0xd9, 0xd9, 0x80, 0x03, 0x00, 0x00,
}
