// Code generated by protoc-gen-go.
// source: proto/wire/game/model.proto
// DO NOT EDIT!

/*
Package game is a generated protocol buffer package.

It is generated from these files:
	proto/wire/game/model.proto

It has these top-level messages:
	Coordinate
	FloatCoordinate
	Player
	Army
	Airplane
	Island
	Game
*/
package game

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Coordinate struct {
	X int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
}

func (m *Coordinate) Reset()                    { *m = Coordinate{} }
func (m *Coordinate) String() string            { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()               {}
func (*Coordinate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Coordinate) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinate) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type FloatCoordinate struct {
	X float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
}

func (m *FloatCoordinate) Reset()                    { *m = FloatCoordinate{} }
func (m *FloatCoordinate) String() string            { return proto.CompactTextString(m) }
func (*FloatCoordinate) ProtoMessage()               {}
func (*FloatCoordinate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FloatCoordinate) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *FloatCoordinate) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Player struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Army struct {
	Owner    *Player `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Strength int32   `protobuf:"varint,2,opt,name=strength" json:"strength,omitempty"`
}

func (m *Army) Reset()                    { *m = Army{} }
func (m *Army) String() string            { return proto.CompactTextString(m) }
func (*Army) ProtoMessage()               {}
func (*Army) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Army) GetOwner() *Player {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Army) GetStrength() int32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

type Airplane struct {
	Id        string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Army      *Army            `protobuf:"bytes,2,opt,name=army" json:"army,omitempty"`
	Position  *FloatCoordinate `protobuf:"bytes,3,opt,name=position" json:"position,omitempty"`
	Direction float32          `protobuf:"fixed32,4,opt,name=direction" json:"direction,omitempty"`
	Speed     float32          `protobuf:"fixed32,5,opt,name=speed" json:"speed,omitempty"`
}

func (m *Airplane) Reset()                    { *m = Airplane{} }
func (m *Airplane) String() string            { return proto.CompactTextString(m) }
func (*Airplane) ProtoMessage()               {}
func (*Airplane) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Airplane) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Airplane) GetArmy() *Army {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *Airplane) GetPosition() *FloatCoordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Airplane) GetDirection() float32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Airplane) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Island struct {
	Id       string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Army     *Army       `protobuf:"bytes,2,opt,name=army" json:"army,omitempty"`
	Position *Coordinate `protobuf:"bytes,3,opt,name=position" json:"position,omitempty"`
	Size     float32     `protobuf:"fixed32,4,opt,name=size" json:"size,omitempty"`
}

func (m *Island) Reset()                    { *m = Island{} }
func (m *Island) String() string            { return proto.CompactTextString(m) }
func (*Island) ProtoMessage()               {}
func (*Island) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Island) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Island) GetArmy() *Army {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *Island) GetPosition() *Coordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Island) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Game struct {
	Id            string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Size          *Coordinate `protobuf:"bytes,2,opt,name=size" json:"size,omitempty"`
	Player1       *Player     `protobuf:"bytes,3,opt,name=player1" json:"player1,omitempty"`
	Player2       *Player     `protobuf:"bytes,4,opt,name=player2" json:"player2,omitempty"`
	PlayerNeutral *Player     `protobuf:"bytes,5,opt,name=player_neutral,json=playerNeutral" json:"player_neutral,omitempty"`
	Islands       []*Island   `protobuf:"bytes,6,rep,name=islands" json:"islands,omitempty"`
	Airplanes     []*Airplane `protobuf:"bytes,7,rep,name=airplanes" json:"airplanes,omitempty"`
}

func (m *Game) Reset()                    { *m = Game{} }
func (m *Game) String() string            { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()               {}
func (*Game) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Game) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Game) GetSize() *Coordinate {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Game) GetPlayer1() *Player {
	if m != nil {
		return m.Player1
	}
	return nil
}

func (m *Game) GetPlayer2() *Player {
	if m != nil {
		return m.Player2
	}
	return nil
}

func (m *Game) GetPlayerNeutral() *Player {
	if m != nil {
		return m.PlayerNeutral
	}
	return nil
}

func (m *Game) GetIslands() []*Island {
	if m != nil {
		return m.Islands
	}
	return nil
}

func (m *Game) GetAirplanes() []*Airplane {
	if m != nil {
		return m.Airplanes
	}
	return nil
}

func init() {
	proto.RegisterType((*Coordinate)(nil), "archipelago.proto.wire.game.Coordinate")
	proto.RegisterType((*FloatCoordinate)(nil), "archipelago.proto.wire.game.FloatCoordinate")
	proto.RegisterType((*Player)(nil), "archipelago.proto.wire.game.Player")
	proto.RegisterType((*Army)(nil), "archipelago.proto.wire.game.Army")
	proto.RegisterType((*Airplane)(nil), "archipelago.proto.wire.game.Airplane")
	proto.RegisterType((*Island)(nil), "archipelago.proto.wire.game.Island")
	proto.RegisterType((*Game)(nil), "archipelago.proto.wire.game.Game")
}

func init() { proto.RegisterFile("proto/wire/game/model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x8b, 0xda, 0x40,
	0x14, 0xc7, 0x49, 0x4c, 0xa2, 0x3e, 0xab, 0xc2, 0xd0, 0x43, 0xa8, 0x3d, 0xd8, 0x94, 0x52, 0x0f,
	0x6d, 0xa4, 0x29, 0x3d, 0x94, 0xd2, 0x83, 0x15, 0xfa, 0xeb, 0x50, 0x4a, 0x8e, 0x85, 0x52, 0x46,
	0x33, 0xe8, 0xc0, 0x24, 0x13, 0x26, 0x29, 0x9a, 0xfd, 0x6f, 0xf6, 0xb6, 0xff, 0xcd, 0xfe, 0x4b,
	0x4b, 0xde, 0x44, 0xc3, 0xaa, 0x64, 0x15, 0xf6, 0x96, 0x37, 0xf3, 0xfd, 0xbc, 0xf7, 0x7d, 0xef,
	0x0d, 0x81, 0x51, 0xaa, 0x64, 0x2e, 0xa7, 0x1b, 0xae, 0xd8, 0x74, 0x45, 0x63, 0x36, 0x8d, 0x65,
	0xc4, 0x84, 0x8f, 0xa7, 0x64, 0x44, 0xd5, 0x72, 0xcd, 0x53, 0x26, 0xe8, 0x4a, 0xea, 0x23, 0xbf,
	0x14, 0xfa, 0xa5, 0xd0, 0x9b, 0x00, 0xcc, 0xa5, 0x54, 0x11, 0x4f, 0x68, 0xce, 0xc8, 0x13, 0x30,
	0xb6, 0xae, 0x31, 0x36, 0x26, 0x76, 0x68, 0x6c, 0xcb, 0xa8, 0x70, 0x4d, 0x1d, 0x15, 0xde, 0x5b,
	0x18, 0x7e, 0x15, 0x92, 0xe6, 0xa7, 0xe4, 0xe6, 0x3d, 0xb9, 0x59, 0xca, 0x5d, 0x70, 0x7e, 0x0b,
	0x5a, 0x30, 0x45, 0x06, 0x60, 0xf2, 0x08, 0x65, 0xdd, 0xd0, 0xe4, 0x91, 0xf7, 0x17, 0xac, 0x99,
	0x8a, 0x0b, 0xf2, 0x11, 0x6c, 0xb9, 0x49, 0x98, 0xc2, 0xab, 0x5e, 0xf0, 0xd2, 0x6f, 0xf0, 0xe9,
	0xeb, 0x5c, 0xa1, 0x26, 0xc8, 0x33, 0xe8, 0x64, 0xb9, 0x62, 0xc9, 0x2a, 0x5f, 0x57, 0x06, 0xf7,
	0xb1, 0x77, 0x6b, 0x40, 0x67, 0xc6, 0x55, 0x2a, 0x68, 0xc2, 0x0e, 0x6b, 0x93, 0x0f, 0x60, 0x51,
	0x15, 0x6b, 0x9b, 0xbd, 0xe0, 0x45, 0x63, 0xc9, 0xd2, 0x64, 0x88, 0x72, 0xf2, 0x1d, 0x3a, 0xa9,
	0xcc, 0x78, 0xce, 0x65, 0xe2, 0xb6, 0x10, 0x7d, 0xd3, 0x88, 0x1e, 0x0c, 0x2a, 0xdc, 0xd3, 0xe4,
	0x39, 0x74, 0x23, 0xae, 0xd8, 0x12, 0x53, 0x59, 0x38, 0xac, 0xfa, 0x80, 0x3c, 0x05, 0x3b, 0x4b,
	0x19, 0x8b, 0x5c, 0x1b, 0x6f, 0x74, 0xe0, 0xdd, 0x18, 0xe0, 0xfc, 0xc8, 0x04, 0x4d, 0xa2, 0xc7,
	0xea, 0x67, 0x7e, 0xd4, 0xcf, 0xeb, 0x46, 0xf4, 0x64, 0x2b, 0x04, 0xac, 0x8c, 0x5f, 0xb1, 0xaa,
	0x0b, 0xfc, 0xf6, 0xae, 0x5b, 0x60, 0x7d, 0xa3, 0xf1, 0xf1, 0xe0, 0x3f, 0x55, 0x62, 0xf3, 0xb2,
	0x6a, 0x08, 0x91, 0xcf, 0xd0, 0x4e, 0x71, 0xff, 0xef, 0x2a, 0xb7, 0x67, 0xbd, 0x95, 0x1d, 0x53,
	0xe3, 0x01, 0x7a, 0xbd, 0x0c, 0x0f, 0xc8, 0x4f, 0x18, 0xe8, 0xcf, 0x7f, 0x09, 0xfb, 0x9f, 0x2b,
	0x2a, 0x70, 0x3b, 0x67, 0x66, 0xe9, 0x6b, 0xf4, 0x97, 0x26, 0x4b, 0x2b, 0x1c, 0x37, 0x99, 0xb9,
	0xce, 0xb8, 0xf5, 0x60, 0x12, 0xbd, 0xf5, 0x70, 0xc7, 0x90, 0x39, 0x74, 0x69, 0xf5, 0xb4, 0x33,
	0xb7, 0x8d, 0x09, 0x5e, 0x35, 0xef, 0xbc, 0x52, 0x87, 0x35, 0xf7, 0x65, 0xf8, 0xa7, 0x2f, 0xf8,
	0xa2, 0xfe, 0x59, 0x2c, 0x1c, 0xa4, 0xde, 0xdf, 0x05, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xe1, 0xa7,
	0xf0, 0x46, 0x04, 0x00, 0x00,
}
