// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wire/msg/game.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PlayerState represents the current exclusive state of a Player.
type PlayerState int32

const (
	// ALIVE is when still alive in the game.
	PlayerState_ALIVE PlayerState = 0
	// PENDING_REVIVAL is when dead, but may be revived.
	PlayerState_PENDING_REVIVAL PlayerState = 1
	// DEAD is when dead and will remain dead.
	PlayerState_DEAD PlayerState = 2
	// LEFT_GAME is when the Player has left the game.
	PlayerState_LEFT_GAME PlayerState = 3
)

var PlayerState_name = map[int32]string{
	0: "ALIVE",
	1: "PENDING_REVIVAL",
	2: "DEAD",
	3: "LEFT_GAME",
}

var PlayerState_value = map[string]int32{
	"ALIVE":           0,
	"PENDING_REVIVAL": 1,
	"DEAD":            2,
	"LEFT_GAME":       3,
}

func (x PlayerState) String() string {
	return proto.EnumName(PlayerState_name, int32(x))
}

func (PlayerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{0}
}

type Coordinate struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{0}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinate) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type FloatCoordinate struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FloatCoordinate) Reset()         { *m = FloatCoordinate{} }
func (m *FloatCoordinate) String() string { return proto.CompactTextString(m) }
func (*FloatCoordinate) ProtoMessage()    {}
func (*FloatCoordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{1}
}

func (m *FloatCoordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatCoordinate.Unmarshal(m, b)
}
func (m *FloatCoordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatCoordinate.Marshal(b, m, deterministic)
}
func (m *FloatCoordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatCoordinate.Merge(m, src)
}
func (m *FloatCoordinate) XXX_Size() int {
	return xxx_messageInfo_FloatCoordinate.Size(m)
}
func (m *FloatCoordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatCoordinate.DiscardUnknown(m)
}

var xxx_messageInfo_FloatCoordinate proto.InternalMessageInfo

func (m *FloatCoordinate) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *FloatCoordinate) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Player struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State                PlayerState `protobuf:"varint,2,opt,name=state,proto3,enum=wire.msg.PlayerState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetState() PlayerState {
	if m != nil {
		return m.State
	}
	return PlayerState_ALIVE
}

type Army struct {
	OwnerId              string   `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Strength             int32    `protobuf:"varint,2,opt,name=strength,proto3" json:"strength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Army) Reset()         { *m = Army{} }
func (m *Army) String() string { return proto.CompactTextString(m) }
func (*Army) ProtoMessage()    {}
func (*Army) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{3}
}

func (m *Army) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Army.Unmarshal(m, b)
}
func (m *Army) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Army.Marshal(b, m, deterministic)
}
func (m *Army) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Army.Merge(m, src)
}
func (m *Army) XXX_Size() int {
	return xxx_messageInfo_Army.Size(m)
}
func (m *Army) XXX_DiscardUnknown() {
	xxx_messageInfo_Army.DiscardUnknown(m)
}

var xxx_messageInfo_Army proto.InternalMessageInfo

func (m *Army) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Army) GetStrength() int32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

type Airplane struct {
	Id        string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Army      *Army            `protobuf:"bytes,2,opt,name=army,proto3" json:"army,omitempty"`
	Position  *FloatCoordinate `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Direction float32          `protobuf:"fixed32,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// Speed of the Airplane [tiles/ms]. Not set if default speed.
	Speed                float32  `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Airplane) Reset()         { *m = Airplane{} }
func (m *Airplane) String() string { return proto.CompactTextString(m) }
func (*Airplane) ProtoMessage()    {}
func (*Airplane) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{4}
}

func (m *Airplane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Airplane.Unmarshal(m, b)
}
func (m *Airplane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Airplane.Marshal(b, m, deterministic)
}
func (m *Airplane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Airplane.Merge(m, src)
}
func (m *Airplane) XXX_Size() int {
	return xxx_messageInfo_Airplane.Size(m)
}
func (m *Airplane) XXX_DiscardUnknown() {
	xxx_messageInfo_Airplane.DiscardUnknown(m)
}

var xxx_messageInfo_Airplane proto.InternalMessageInfo

func (m *Airplane) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Airplane) GetArmy() *Army {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *Airplane) GetPosition() *FloatCoordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Airplane) GetDirection() float32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Airplane) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Island struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Army                 *Army       `protobuf:"bytes,2,opt,name=army,proto3" json:"army,omitempty"`
	Position             *Coordinate `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Size                 float32     `protobuf:"fixed32,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Island) Reset()         { *m = Island{} }
func (m *Island) String() string { return proto.CompactTextString(m) }
func (*Island) ProtoMessage()    {}
func (*Island) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{5}
}

func (m *Island) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Island.Unmarshal(m, b)
}
func (m *Island) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Island.Marshal(b, m, deterministic)
}
func (m *Island) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Island.Merge(m, src)
}
func (m *Island) XXX_Size() int {
	return xxx_messageInfo_Island.Size(m)
}
func (m *Island) XXX_DiscardUnknown() {
	xxx_messageInfo_Island.DiscardUnknown(m)
}

var xxx_messageInfo_Island proto.InternalMessageInfo

func (m *Island) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Island) GetArmy() *Army {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *Island) GetPosition() *Coordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Island) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Game struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 *Coordinate `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	PlayerNeutral        *Player     `protobuf:"bytes,3,opt,name=player_neutral,json=playerNeutral,proto3" json:"player_neutral,omitempty"`
	Players              []*Player   `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	Islands              []*Island   `protobuf:"bytes,5,rep,name=islands,proto3" json:"islands,omitempty"`
	Airplanes            []*Airplane `protobuf:"bytes,6,rep,name=airplanes,proto3" json:"airplanes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{6}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Game) GetSize() *Coordinate {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Game) GetPlayerNeutral() *Player {
	if m != nil {
		return m.PlayerNeutral
	}
	return nil
}

func (m *Game) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Game) GetIslands() []*Island {
	if m != nil {
		return m.Islands
	}
	return nil
}

func (m *Game) GetAirplanes() []*Airplane {
	if m != nil {
		return m.Airplanes
	}
	return nil
}

type EventEnvelope struct {
	// Types that are valid to be assigned to Event:
	//	*EventEnvelope_EventGameStart
	//	*EventEnvelope_EventGameOver
	//	*EventEnvelope_EventGameTick
	Event                isEventEnvelope_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventEnvelope) Reset()         { *m = EventEnvelope{} }
func (m *EventEnvelope) String() string { return proto.CompactTextString(m) }
func (*EventEnvelope) ProtoMessage()    {}
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{7}
}

func (m *EventEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventEnvelope.Unmarshal(m, b)
}
func (m *EventEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventEnvelope.Marshal(b, m, deterministic)
}
func (m *EventEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventEnvelope.Merge(m, src)
}
func (m *EventEnvelope) XXX_Size() int {
	return xxx_messageInfo_EventEnvelope.Size(m)
}
func (m *EventEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_EventEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_EventEnvelope proto.InternalMessageInfo

type isEventEnvelope_Event interface {
	isEventEnvelope_Event()
}

type EventEnvelope_EventGameStart struct {
	EventGameStart *EventGameStart `protobuf:"bytes,1,opt,name=event_game_start,json=eventGameStart,proto3,oneof"`
}

type EventEnvelope_EventGameOver struct {
	EventGameOver *EventGameOver `protobuf:"bytes,2,opt,name=event_game_over,json=eventGameOver,proto3,oneof"`
}

type EventEnvelope_EventGameTick struct {
	EventGameTick *EventGameTick `protobuf:"bytes,3,opt,name=event_game_tick,json=eventGameTick,proto3,oneof"`
}

func (*EventEnvelope_EventGameStart) isEventEnvelope_Event() {}

func (*EventEnvelope_EventGameOver) isEventEnvelope_Event() {}

func (*EventEnvelope_EventGameTick) isEventEnvelope_Event() {}

func (m *EventEnvelope) GetEvent() isEventEnvelope_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *EventEnvelope) GetEventGameStart() *EventGameStart {
	if x, ok := m.GetEvent().(*EventEnvelope_EventGameStart); ok {
		return x.EventGameStart
	}
	return nil
}

func (m *EventEnvelope) GetEventGameOver() *EventGameOver {
	if x, ok := m.GetEvent().(*EventEnvelope_EventGameOver); ok {
		return x.EventGameOver
	}
	return nil
}

func (m *EventEnvelope) GetEventGameTick() *EventGameTick {
	if x, ok := m.GetEvent().(*EventEnvelope_EventGameTick); ok {
		return x.EventGameTick
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventEnvelope) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventEnvelope_EventGameStart)(nil),
		(*EventEnvelope_EventGameOver)(nil),
		(*EventEnvelope_EventGameTick)(nil),
	}
}

type EventGameStart struct {
	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Aprox. time between ticks [ms].
	TickInterval         uint32   `protobuf:"varint,2,opt,name=tick_interval,json=tickInterval,proto3" json:"tick_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventGameStart) Reset()         { *m = EventGameStart{} }
func (m *EventGameStart) String() string { return proto.CompactTextString(m) }
func (*EventGameStart) ProtoMessage()    {}
func (*EventGameStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{8}
}

func (m *EventGameStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGameStart.Unmarshal(m, b)
}
func (m *EventGameStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGameStart.Marshal(b, m, deterministic)
}
func (m *EventGameStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGameStart.Merge(m, src)
}
func (m *EventGameStart) XXX_Size() int {
	return xxx_messageInfo_EventGameStart.Size(m)
}
func (m *EventGameStart) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGameStart.DiscardUnknown(m)
}

var xxx_messageInfo_EventGameStart proto.InternalMessageInfo

func (m *EventGameStart) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *EventGameStart) GetTickInterval() uint32 {
	if m != nil {
		return m.TickInterval
	}
	return 0
}

type EventGameOver struct {
	WinnerId             string   `protobuf:"bytes,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventGameOver) Reset()         { *m = EventGameOver{} }
func (m *EventGameOver) String() string { return proto.CompactTextString(m) }
func (*EventGameOver) ProtoMessage()    {}
func (*EventGameOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{9}
}

func (m *EventGameOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGameOver.Unmarshal(m, b)
}
func (m *EventGameOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGameOver.Marshal(b, m, deterministic)
}
func (m *EventGameOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGameOver.Merge(m, src)
}
func (m *EventGameOver) XXX_Size() int {
	return xxx_messageInfo_EventGameOver.Size(m)
}
func (m *EventGameOver) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGameOver.DiscardUnknown(m)
}

var xxx_messageInfo_EventGameOver proto.InternalMessageInfo

func (m *EventGameOver) GetWinnerId() string {
	if m != nil {
		return m.WinnerId
	}
	return ""
}

type EventGameTick struct {
	Game                 *Game    `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventGameTick) Reset()         { *m = EventGameTick{} }
func (m *EventGameTick) String() string { return proto.CompactTextString(m) }
func (*EventGameTick) ProtoMessage()    {}
func (*EventGameTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{10}
}

func (m *EventGameTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGameTick.Unmarshal(m, b)
}
func (m *EventGameTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGameTick.Marshal(b, m, deterministic)
}
func (m *EventGameTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGameTick.Merge(m, src)
}
func (m *EventGameTick) XXX_Size() int {
	return xxx_messageInfo_EventGameTick.Size(m)
}
func (m *EventGameTick) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGameTick.DiscardUnknown(m)
}

var xxx_messageInfo_EventGameTick proto.InternalMessageInfo

func (m *EventGameTick) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type ActionEnvelope struct {
	// Types that are valid to be assigned to Action:
	//	*ActionEnvelope_ActionGameLeave
	//	*ActionEnvelope_ActionGameLaunch
	Action               isActionEnvelope_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ActionEnvelope) Reset()         { *m = ActionEnvelope{} }
func (m *ActionEnvelope) String() string { return proto.CompactTextString(m) }
func (*ActionEnvelope) ProtoMessage()    {}
func (*ActionEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{11}
}

func (m *ActionEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionEnvelope.Unmarshal(m, b)
}
func (m *ActionEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionEnvelope.Marshal(b, m, deterministic)
}
func (m *ActionEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionEnvelope.Merge(m, src)
}
func (m *ActionEnvelope) XXX_Size() int {
	return xxx_messageInfo_ActionEnvelope.Size(m)
}
func (m *ActionEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ActionEnvelope proto.InternalMessageInfo

type isActionEnvelope_Action interface {
	isActionEnvelope_Action()
}

type ActionEnvelope_ActionGameLeave struct {
	ActionGameLeave *ActionGameLeave `protobuf:"bytes,1,opt,name=action_game_leave,json=actionGameLeave,proto3,oneof"`
}

type ActionEnvelope_ActionGameLaunch struct {
	ActionGameLaunch *ActionGameLaunch `protobuf:"bytes,2,opt,name=action_game_launch,json=actionGameLaunch,proto3,oneof"`
}

func (*ActionEnvelope_ActionGameLeave) isActionEnvelope_Action() {}

func (*ActionEnvelope_ActionGameLaunch) isActionEnvelope_Action() {}

func (m *ActionEnvelope) GetAction() isActionEnvelope_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ActionEnvelope) GetActionGameLeave() *ActionGameLeave {
	if x, ok := m.GetAction().(*ActionEnvelope_ActionGameLeave); ok {
		return x.ActionGameLeave
	}
	return nil
}

func (m *ActionEnvelope) GetActionGameLaunch() *ActionGameLaunch {
	if x, ok := m.GetAction().(*ActionEnvelope_ActionGameLaunch); ok {
		return x.ActionGameLaunch
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ActionEnvelope) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ActionEnvelope_ActionGameLeave)(nil),
		(*ActionEnvelope_ActionGameLaunch)(nil),
	}
}

type ActionGameLeave struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionGameLeave) Reset()         { *m = ActionGameLeave{} }
func (m *ActionGameLeave) String() string { return proto.CompactTextString(m) }
func (*ActionGameLeave) ProtoMessage()    {}
func (*ActionGameLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{12}
}

func (m *ActionGameLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionGameLeave.Unmarshal(m, b)
}
func (m *ActionGameLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionGameLeave.Marshal(b, m, deterministic)
}
func (m *ActionGameLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionGameLeave.Merge(m, src)
}
func (m *ActionGameLeave) XXX_Size() int {
	return xxx_messageInfo_ActionGameLeave.Size(m)
}
func (m *ActionGameLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionGameLeave.DiscardUnknown(m)
}

var xxx_messageInfo_ActionGameLeave proto.InternalMessageInfo

type ActionGameLaunch struct {
	FromId               string   `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId                 string   `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionGameLaunch) Reset()         { *m = ActionGameLaunch{} }
func (m *ActionGameLaunch) String() string { return proto.CompactTextString(m) }
func (*ActionGameLaunch) ProtoMessage()    {}
func (*ActionGameLaunch) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2c083f9196954d, []int{13}
}

func (m *ActionGameLaunch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionGameLaunch.Unmarshal(m, b)
}
func (m *ActionGameLaunch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionGameLaunch.Marshal(b, m, deterministic)
}
func (m *ActionGameLaunch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionGameLaunch.Merge(m, src)
}
func (m *ActionGameLaunch) XXX_Size() int {
	return xxx_messageInfo_ActionGameLaunch.Size(m)
}
func (m *ActionGameLaunch) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionGameLaunch.DiscardUnknown(m)
}

var xxx_messageInfo_ActionGameLaunch proto.InternalMessageInfo

func (m *ActionGameLaunch) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *ActionGameLaunch) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func init() {
	proto.RegisterEnum("wire.msg.PlayerState", PlayerState_name, PlayerState_value)
	proto.RegisterType((*Coordinate)(nil), "wire.msg.Coordinate")
	proto.RegisterType((*FloatCoordinate)(nil), "wire.msg.FloatCoordinate")
	proto.RegisterType((*Player)(nil), "wire.msg.Player")
	proto.RegisterType((*Army)(nil), "wire.msg.Army")
	proto.RegisterType((*Airplane)(nil), "wire.msg.Airplane")
	proto.RegisterType((*Island)(nil), "wire.msg.Island")
	proto.RegisterType((*Game)(nil), "wire.msg.Game")
	proto.RegisterType((*EventEnvelope)(nil), "wire.msg.EventEnvelope")
	proto.RegisterType((*EventGameStart)(nil), "wire.msg.EventGameStart")
	proto.RegisterType((*EventGameOver)(nil), "wire.msg.EventGameOver")
	proto.RegisterType((*EventGameTick)(nil), "wire.msg.EventGameTick")
	proto.RegisterType((*ActionEnvelope)(nil), "wire.msg.ActionEnvelope")
	proto.RegisterType((*ActionGameLeave)(nil), "wire.msg.ActionGameLeave")
	proto.RegisterType((*ActionGameLaunch)(nil), "wire.msg.ActionGameLaunch")
}

func init() { proto.RegisterFile("wire/msg/game.proto", fileDescriptor_8c2c083f9196954d) }

var fileDescriptor_8c2c083f9196954d = []byte{
	// 751 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x4d, 0x4f, 0xe3, 0x46,
	0x1c, 0xc6, 0x63, 0x63, 0x27, 0xce, 0x1f, 0x92, 0x98, 0x81, 0x0a, 0x03, 0x3d, 0x20, 0xf7, 0x82,
	0x28, 0x4d, 0x10, 0xa8, 0xea, 0xa9, 0x52, 0x4d, 0x63, 0x12, 0x57, 0x29, 0x45, 0x03, 0xe2, 0xd0,
	0x4b, 0x34, 0xc4, 0xd3, 0x64, 0x84, 0x5f, 0xa2, 0xf1, 0x10, 0x48, 0x8f, 0xbb, 0x9f, 0x66, 0x4f,
	0xfb, 0xa5, 0xf6, 0x83, 0xac, 0x66, 0xec, 0xbc, 0x12, 0xed, 0x61, 0x6f, 0xcc, 0x33, 0xbf, 0x79,
	0xfc, 0xf0, 0xfc, 0x3d, 0x31, 0xec, 0xbd, 0x32, 0x4e, 0x5b, 0x71, 0x36, 0x6c, 0x0d, 0x49, 0x4c,
	0x9b, 0x63, 0x9e, 0x8a, 0x14, 0x59, 0x52, 0x6c, 0xc6, 0xd9, 0xd0, 0x3d, 0x05, 0xf8, 0x33, 0x4d,
	0x79, 0xc8, 0x12, 0x22, 0x28, 0xda, 0x01, 0xed, 0xcd, 0xd1, 0x4e, 0xb4, 0x53, 0x13, 0x6b, 0x6f,
	0x72, 0x35, 0x75, 0xf4, 0x7c, 0x35, 0x75, 0x7f, 0x81, 0xc6, 0x4d, 0x94, 0x12, 0xb1, 0x09, 0xd7,
	0x57, 0x70, 0x5d, 0xe2, 0x3e, 0x94, 0xef, 0x22, 0x32, 0xa5, 0x1c, 0xd5, 0x41, 0x67, 0xa1, 0xc2,
	0xaa, 0x58, 0x67, 0x21, 0xfa, 0x19, 0xcc, 0x4c, 0x10, 0x41, 0x15, 0x5b, 0xbf, 0xfc, 0xa1, 0x39,
	0x0b, 0xd3, 0xcc, 0x0f, 0xdc, 0xcb, 0x4d, 0x9c, 0x33, 0xee, 0xef, 0x60, 0x78, 0x3c, 0x9e, 0xa2,
	0x43, 0xb0, 0xd2, 0xd7, 0x84, 0xf2, 0xfe, 0xdc, 0xaa, 0xa2, 0xd6, 0x41, 0x88, 0x8e, 0xc0, 0xca,
	0x04, 0xa7, 0xc9, 0x50, 0x8c, 0x8a, 0xb4, 0xf3, 0xb5, 0xfb, 0x49, 0x03, 0xcb, 0x63, 0x7c, 0x1c,
	0x91, 0x84, 0xbe, 0x0b, 0xe2, 0x82, 0x41, 0x78, 0x9c, 0x67, 0xde, 0xbe, 0xac, 0x2f, 0x72, 0xc8,
	0x27, 0x62, 0xb5, 0x87, 0x7e, 0x05, 0x6b, 0x9c, 0x66, 0x4c, 0xb0, 0x34, 0x71, 0xb6, 0x14, 0x77,
	0xb8, 0xe0, 0xd6, 0xfa, 0xc0, 0x73, 0x14, 0xfd, 0x08, 0xd5, 0x90, 0x71, 0x3a, 0x50, 0xe7, 0x0c,
	0xd5, 0xc9, 0x42, 0x40, 0xfb, 0x60, 0x66, 0x63, 0x4a, 0x43, 0xc7, 0x54, 0x3b, 0xf9, 0xc2, 0xfd,
	0xa0, 0x41, 0x39, 0xc8, 0x22, 0x92, 0x84, 0xdf, 0x95, 0xf4, 0xe2, 0x5d, 0xd2, 0xfd, 0x05, 0xb7,
	0x31, 0x24, 0x02, 0x23, 0x63, 0xff, 0xd3, 0x22, 0x9f, 0xfa, 0xdb, 0xfd, 0xa8, 0x83, 0xd1, 0x21,
	0xf1, 0xfb, 0xb2, 0x4e, 0x0b, 0x58, 0xff, 0x86, 0xb5, 0x22, 0xd0, 0x6f, 0x50, 0x1f, 0xab, 0x41,
	0xf6, 0x13, 0xfa, 0x22, 0x38, 0x89, 0x8a, 0x38, 0xf6, 0xfa, 0xa0, 0x71, 0x2d, 0xe7, 0x6e, 0x73,
	0x0c, 0x9d, 0x41, 0x25, 0x17, 0x32, 0xc7, 0x38, 0xd9, 0xda, 0x78, 0x62, 0x06, 0x48, 0x96, 0xa9,
	0xae, 0x32, 0xc7, 0x5c, 0x67, 0xf3, 0x12, 0xf1, 0x0c, 0x40, 0x17, 0x50, 0x25, 0xc5, 0x3b, 0x90,
	0x39, 0x65, 0x45, 0xa3, 0xa5, 0x0a, 0x8b, 0x2d, 0xbc, 0x80, 0xdc, 0x2f, 0x1a, 0xd4, 0xfc, 0x09,
	0x4d, 0x84, 0x9f, 0x4c, 0x68, 0x94, 0x8e, 0x29, 0x6a, 0x83, 0x4d, 0xa5, 0xd0, 0x97, 0xb7, 0xa8,
	0x9f, 0x09, 0xc2, 0x85, 0x2a, 0x67, 0xfb, 0xd2, 0x59, 0x58, 0xa9, 0x23, 0xb2, 0xbd, 0x7b, 0xb9,
	0xdf, 0x2d, 0xe1, 0x3a, 0x5d, 0x51, 0x90, 0x07, 0x8d, 0x25, 0x97, 0x74, 0x42, 0x79, 0xd1, 0xe7,
	0xc1, 0x06, 0x93, 0x7f, 0x26, 0x94, 0x77, 0x4b, 0xb8, 0x46, 0x97, 0x85, 0x35, 0x0b, 0xc1, 0x06,
	0xcf, 0x45, 0xbd, 0x9b, 0x2c, 0x1e, 0xd8, 0xe0, 0x79, 0xc5, 0x42, 0x0a, 0xd7, 0x15, 0x30, 0x95,
	0xe0, 0x62, 0xa8, 0xaf, 0x46, 0x46, 0xc7, 0x50, 0x2d, 0x66, 0x37, 0x1f, 0xbe, 0x95, 0x0b, 0x41,
	0x88, 0x7e, 0x82, 0x9a, 0x7c, 0x5e, 0x9f, 0x25, 0x82, 0xf2, 0x09, 0x89, 0x54, 0xf6, 0x1a, 0xde,
	0x91, 0x62, 0x50, 0x68, 0xee, 0x79, 0xd1, 0xdc, 0x3c, 0xf0, 0x31, 0x54, 0x5f, 0x59, 0xb2, 0x72,
	0x75, 0xad, 0x5c, 0x08, 0x42, 0xf7, 0x6a, 0x89, 0x96, 0xd9, 0xe4, 0x9b, 0x2e, 0xff, 0xb1, 0xa2,
	0xdb, 0xa5, 0x37, 0x5d, 0x12, 0x58, 0xed, 0xb9, 0x9f, 0x35, 0xa8, 0x7b, 0xea, 0x26, 0xcd, 0xc7,
	0xd3, 0x81, 0x5d, 0xa2, 0x94, 0xbc, 0x96, 0x88, 0x92, 0xc9, 0xcc, 0x63, 0xe9, 0xbe, 0xe6, 0x87,
	0xa4, 0x53, 0x4f, 0x02, 0xdd, 0x12, 0x6e, 0x90, 0x55, 0x09, 0xfd, 0x05, 0x68, 0xc5, 0x88, 0xbc,
	0x24, 0x83, 0x51, 0x31, 0xa4, 0xa3, 0x8d, 0x4e, 0x8a, 0xe8, 0x96, 0xb0, 0x4d, 0xd6, 0xb4, 0x6b,
	0x0b, 0xca, 0xb9, 0xe6, 0xee, 0x42, 0x63, 0xed, 0xd9, 0xee, 0x1f, 0x60, 0xaf, 0x9b, 0xa0, 0x03,
	0xa8, 0xfc, 0xc7, 0xd3, 0x78, 0x51, 0x54, 0x59, 0x2e, 0x83, 0x10, 0xed, 0x81, 0x29, 0x52, 0x29,
	0xeb, 0x4a, 0x36, 0x44, 0x1a, 0x84, 0x67, 0x37, 0xb0, 0xbd, 0xf4, 0x83, 0x89, 0xaa, 0x60, 0x7a,
	0xbd, 0xe0, 0xd1, 0xb7, 0x4b, 0x68, 0x0f, 0x1a, 0x77, 0xfe, 0x6d, 0x3b, 0xb8, 0xed, 0xf4, 0xb1,
	0xff, 0x18, 0x3c, 0x7a, 0x3d, 0x5b, 0x43, 0x16, 0x18, 0x6d, 0xdf, 0x6b, 0xdb, 0x3a, 0xaa, 0x41,
	0xb5, 0xe7, 0xdf, 0x3c, 0xf4, 0x3b, 0xde, 0xdf, 0xbe, 0xbd, 0x75, 0x7d, 0xfe, 0xef, 0xd9, 0x90,
	0x89, 0xd1, 0xcb, 0x53, 0x73, 0x90, 0xc6, 0xad, 0x09, 0xe5, 0x44, 0x8c, 0x5a, 0x84, 0x0f, 0x46,
	0x6c, 0x4c, 0x23, 0x32, 0x4c, 0x5b, 0x11, 0x7b, 0x6a, 0xcd, 0xbe, 0x22, 0x4f, 0x65, 0xf5, 0x05,
	0xb9, 0xfa, 0x1a, 0x00, 0x00, 0xff, 0xff, 0xae, 0x3a, 0xb6, 0x0c, 0x58, 0x06, 0x00, 0x00,
}
