// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: wire/msg/game.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlayerState represents the current exclusive state of a Player.
type PlayerState int32

const (
	// ALIVE is when still alive in the game.
	PlayerState_ALIVE PlayerState = 0
	// PENDING_REVIVAL is when dead, but may be revived.
	PlayerState_PENDING_REVIVAL PlayerState = 1
	// DEAD is when dead and will remain dead.
	PlayerState_DEAD PlayerState = 2
	// LEFT_GAME is when the Player has left the game.
	PlayerState_LEFT_GAME PlayerState = 3
)

// Enum value maps for PlayerState.
var (
	PlayerState_name = map[int32]string{
		0: "ALIVE",
		1: "PENDING_REVIVAL",
		2: "DEAD",
		3: "LEFT_GAME",
	}
	PlayerState_value = map[string]int32{
		"ALIVE":           0,
		"PENDING_REVIVAL": 1,
		"DEAD":            2,
		"LEFT_GAME":       3,
	}
)

func (x PlayerState) Enum() *PlayerState {
	p := new(PlayerState)
	*p = x
	return p
}

func (x PlayerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerState) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_msg_game_proto_enumTypes[0].Descriptor()
}

func (PlayerState) Type() protoreflect.EnumType {
	return &file_wire_msg_game_proto_enumTypes[0]
}

func (x PlayerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerState.Descriptor instead.
func (PlayerState) EnumDescriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{0}
}

type Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FloatCoordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *FloatCoordinate) Reset() {
	*x = FloatCoordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatCoordinate) ProtoMessage() {}

func (x *FloatCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatCoordinate.ProtoReflect.Descriptor instead.
func (*FloatCoordinate) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{1}
}

func (x *FloatCoordinate) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FloatCoordinate) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State PlayerState `protobuf:"varint,2,opt,name=state,proto3,enum=wire.msg.PlayerState" json:"state,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetState() PlayerState {
	if x != nil {
		return x.State
	}
	return PlayerState_ALIVE
}

type Army struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId  string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Strength int32  `protobuf:"varint,2,opt,name=strength,proto3" json:"strength,omitempty"`
}

func (x *Army) Reset() {
	*x = Army{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Army) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Army) ProtoMessage() {}

func (x *Army) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Army.ProtoReflect.Descriptor instead.
func (*Army) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{3}
}

func (x *Army) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Army) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

type Airplane struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Army      *Army            `protobuf:"bytes,2,opt,name=army,proto3" json:"army,omitempty"`
	Position  *FloatCoordinate `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Direction float32          `protobuf:"fixed32,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// Speed of the Airplane [tiles/ms]. Not set if default speed.
	Speed float32 `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *Airplane) Reset() {
	*x = Airplane{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Airplane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airplane) ProtoMessage() {}

func (x *Airplane) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airplane.ProtoReflect.Descriptor instead.
func (*Airplane) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{4}
}

func (x *Airplane) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Airplane) GetArmy() *Army {
	if x != nil {
		return x.Army
	}
	return nil
}

func (x *Airplane) GetPosition() *FloatCoordinate {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Airplane) GetDirection() float32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *Airplane) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type Island struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Army     *Army       `protobuf:"bytes,2,opt,name=army,proto3" json:"army,omitempty"`
	Position *Coordinate `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Size     float32     `protobuf:"fixed32,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Island) Reset() {
	*x = Island{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Island) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Island) ProtoMessage() {}

func (x *Island) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Island.ProtoReflect.Descriptor instead.
func (*Island) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{5}
}

func (x *Island) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Island) GetArmy() *Army {
	if x != nil {
		return x.Army
	}
	return nil
}

func (x *Island) GetPosition() *Coordinate {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Island) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          *Coordinate `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	PlayerNeutral *Player     `protobuf:"bytes,3,opt,name=player_neutral,json=playerNeutral,proto3" json:"player_neutral,omitempty"`
	Players       []*Player   `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	Islands       []*Island   `protobuf:"bytes,5,rep,name=islands,proto3" json:"islands,omitempty"`
	Airplanes     []*Airplane `protobuf:"bytes,6,rep,name=airplanes,proto3" json:"airplanes,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{6}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetSize() *Coordinate {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Game) GetPlayerNeutral() *Player {
	if x != nil {
		return x.PlayerNeutral
	}
	return nil
}

func (x *Game) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Game) GetIslands() []*Island {
	if x != nil {
		return x.Islands
	}
	return nil
}

func (x *Game) GetAirplanes() []*Airplane {
	if x != nil {
		return x.Airplanes
	}
	return nil
}

type EventEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*EventEnvelope_EventGameStart
	//	*EventEnvelope_EventGameOver
	//	*EventEnvelope_EventGameTick
	Event isEventEnvelope_Event `protobuf_oneof:"event"`
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{7}
}

func (m *EventEnvelope) GetEvent() isEventEnvelope_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *EventEnvelope) GetEventGameStart() *EventGameStart {
	if x, ok := x.GetEvent().(*EventEnvelope_EventGameStart); ok {
		return x.EventGameStart
	}
	return nil
}

func (x *EventEnvelope) GetEventGameOver() *EventGameOver {
	if x, ok := x.GetEvent().(*EventEnvelope_EventGameOver); ok {
		return x.EventGameOver
	}
	return nil
}

func (x *EventEnvelope) GetEventGameTick() *EventGameTick {
	if x, ok := x.GetEvent().(*EventEnvelope_EventGameTick); ok {
		return x.EventGameTick
	}
	return nil
}

type isEventEnvelope_Event interface {
	isEventEnvelope_Event()
}

type EventEnvelope_EventGameStart struct {
	EventGameStart *EventGameStart `protobuf:"bytes,1,opt,name=event_game_start,json=eventGameStart,proto3,oneof"`
}

type EventEnvelope_EventGameOver struct {
	EventGameOver *EventGameOver `protobuf:"bytes,2,opt,name=event_game_over,json=eventGameOver,proto3,oneof"`
}

type EventEnvelope_EventGameTick struct {
	EventGameTick *EventGameTick `protobuf:"bytes,3,opt,name=event_game_tick,json=eventGameTick,proto3,oneof"`
}

func (*EventEnvelope_EventGameStart) isEventEnvelope_Event() {}

func (*EventEnvelope_EventGameOver) isEventEnvelope_Event() {}

func (*EventEnvelope_EventGameTick) isEventEnvelope_Event() {}

type EventGameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Aprox. time between ticks [ms].
	TickInterval uint32 `protobuf:"varint,2,opt,name=tick_interval,json=tickInterval,proto3" json:"tick_interval,omitempty"`
}

func (x *EventGameStart) Reset() {
	*x = EventGameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventGameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGameStart) ProtoMessage() {}

func (x *EventGameStart) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventGameStart.ProtoReflect.Descriptor instead.
func (*EventGameStart) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{8}
}

func (x *EventGameStart) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *EventGameStart) GetTickInterval() uint32 {
	if x != nil {
		return x.TickInterval
	}
	return 0
}

type EventGameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinnerId string `protobuf:"bytes,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
}

func (x *EventGameOver) Reset() {
	*x = EventGameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventGameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGameOver) ProtoMessage() {}

func (x *EventGameOver) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventGameOver.ProtoReflect.Descriptor instead.
func (*EventGameOver) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{9}
}

func (x *EventGameOver) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

type EventGameTick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *EventGameTick) Reset() {
	*x = EventGameTick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventGameTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGameTick) ProtoMessage() {}

func (x *EventGameTick) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventGameTick.ProtoReflect.Descriptor instead.
func (*EventGameTick) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{10}
}

func (x *EventGameTick) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type ActionEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//	*ActionEnvelope_ActionGameLeave
	//	*ActionEnvelope_ActionGameLaunch
	Action isActionEnvelope_Action `protobuf_oneof:"action"`
}

func (x *ActionEnvelope) Reset() {
	*x = ActionEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEnvelope) ProtoMessage() {}

func (x *ActionEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEnvelope.ProtoReflect.Descriptor instead.
func (*ActionEnvelope) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{11}
}

func (m *ActionEnvelope) GetAction() isActionEnvelope_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *ActionEnvelope) GetActionGameLeave() *ActionGameLeave {
	if x, ok := x.GetAction().(*ActionEnvelope_ActionGameLeave); ok {
		return x.ActionGameLeave
	}
	return nil
}

func (x *ActionEnvelope) GetActionGameLaunch() *ActionGameLaunch {
	if x, ok := x.GetAction().(*ActionEnvelope_ActionGameLaunch); ok {
		return x.ActionGameLaunch
	}
	return nil
}

type isActionEnvelope_Action interface {
	isActionEnvelope_Action()
}

type ActionEnvelope_ActionGameLeave struct {
	ActionGameLeave *ActionGameLeave `protobuf:"bytes,1,opt,name=action_game_leave,json=actionGameLeave,proto3,oneof"`
}

type ActionEnvelope_ActionGameLaunch struct {
	ActionGameLaunch *ActionGameLaunch `protobuf:"bytes,2,opt,name=action_game_launch,json=actionGameLaunch,proto3,oneof"`
}

func (*ActionEnvelope_ActionGameLeave) isActionEnvelope_Action() {}

func (*ActionEnvelope_ActionGameLaunch) isActionEnvelope_Action() {}

type ActionGameLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActionGameLeave) Reset() {
	*x = ActionGameLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionGameLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionGameLeave) ProtoMessage() {}

func (x *ActionGameLeave) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionGameLeave.ProtoReflect.Descriptor instead.
func (*ActionGameLeave) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{12}
}

type ActionGameLaunch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromId string `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId   string `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
}

func (x *ActionGameLaunch) Reset() {
	*x = ActionGameLaunch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wire_msg_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionGameLaunch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionGameLaunch) ProtoMessage() {}

func (x *ActionGameLaunch) ProtoReflect() protoreflect.Message {
	mi := &file_wire_msg_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionGameLaunch.ProtoReflect.Descriptor instead.
func (*ActionGameLaunch) Descriptor() ([]byte, []int) {
	return file_wire_msg_game_proto_rawDescGZIP(), []int{13}
}

func (x *ActionGameLaunch) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *ActionGameLaunch) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

var File_wire_msg_game_proto protoreflect.FileDescriptor

var file_wire_msg_game_proto_rawDesc = []byte{
	0x0a, 0x13, 0x77, 0x69, 0x72, 0x65, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x22,
	0x28, 0x0a, 0x0a, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x2d, 0x0a, 0x0f, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x45, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x3d, 0x0a, 0x04, 0x41, 0x72, 0x6d, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0xa9,
	0x01, 0x0a, 0x08, 0x41, 0x69, 0x72, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x61,
	0x72, 0x6d, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x77, 0x69, 0x72, 0x65,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x04, 0x61, 0x72, 0x6d, 0x79, 0x12,
	0x35, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x06, 0x49,
	0x73, 0x6c, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x61, 0x72, 0x6d, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x41,
	0x72, 0x6d, 0x79, 0x52, 0x04, 0x61, 0x72, 0x6d, 0x79, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77, 0x69,
	0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0x83, 0x02, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x65, 0x75,
	0x74, 0x72, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x77, 0x69, 0x72,
	0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0d, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x69, 0x73, 0x6c, 0x61, 0x6e,
	0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x49, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x69, 0x73, 0x6c, 0x61,
	0x6e, 0x64, 0x73, 0x12, 0x30, 0x0a, 0x09, 0x61, 0x69, 0x72, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x41, 0x69, 0x72, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x52, 0x09, 0x61, 0x69, 0x72, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x73, 0x22, 0xe4, 0x01, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x41, 0x0a,
	0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72,
	0x12, 0x41, 0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74,
	0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77, 0x69, 0x72, 0x65,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x69,
	0x63, 0x6b, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x52, 0x0a, 0x0e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74,
	0x69, 0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c,
	0x22, 0x2c, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x33,
	0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x12,
	0x22, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67,
	0x61, 0x6d, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x47, 0x0a, 0x11, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x48, 0x00, 0x52, 0x0f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12,
	0x4a, 0x0a, 0x12, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x69,
	0x72, 0x65, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x61, 0x6d,
	0x65, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x48, 0x00, 0x52, 0x10, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x42, 0x08, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47,
	0x61, 0x6d, 0x65, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x22, 0x40, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x12, 0x17, 0x0a, 0x07,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x64, 0x2a, 0x46, 0x0a, 0x0b, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4c, 0x49,
	0x56, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x5f,
	0x52, 0x45, 0x56, 0x49, 0x56, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x41,
	0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x45, 0x46, 0x54, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x10, 0x03, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x76, 0x65, 0x72, 0x61, 0x74, 0x68, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x70, 0x65, 0x6c,
	0x61, 0x67, 0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x2f, 0x6d, 0x73, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wire_msg_game_proto_rawDescOnce sync.Once
	file_wire_msg_game_proto_rawDescData = file_wire_msg_game_proto_rawDesc
)

func file_wire_msg_game_proto_rawDescGZIP() []byte {
	file_wire_msg_game_proto_rawDescOnce.Do(func() {
		file_wire_msg_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_wire_msg_game_proto_rawDescData)
	})
	return file_wire_msg_game_proto_rawDescData
}

var file_wire_msg_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wire_msg_game_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_wire_msg_game_proto_goTypes = []interface{}{
	(PlayerState)(0),         // 0: wire.msg.PlayerState
	(*Coordinate)(nil),       // 1: wire.msg.Coordinate
	(*FloatCoordinate)(nil),  // 2: wire.msg.FloatCoordinate
	(*Player)(nil),           // 3: wire.msg.Player
	(*Army)(nil),             // 4: wire.msg.Army
	(*Airplane)(nil),         // 5: wire.msg.Airplane
	(*Island)(nil),           // 6: wire.msg.Island
	(*Game)(nil),             // 7: wire.msg.Game
	(*EventEnvelope)(nil),    // 8: wire.msg.EventEnvelope
	(*EventGameStart)(nil),   // 9: wire.msg.EventGameStart
	(*EventGameOver)(nil),    // 10: wire.msg.EventGameOver
	(*EventGameTick)(nil),    // 11: wire.msg.EventGameTick
	(*ActionEnvelope)(nil),   // 12: wire.msg.ActionEnvelope
	(*ActionGameLeave)(nil),  // 13: wire.msg.ActionGameLeave
	(*ActionGameLaunch)(nil), // 14: wire.msg.ActionGameLaunch
}
var file_wire_msg_game_proto_depIdxs = []int32{
	0,  // 0: wire.msg.Player.state:type_name -> wire.msg.PlayerState
	4,  // 1: wire.msg.Airplane.army:type_name -> wire.msg.Army
	2,  // 2: wire.msg.Airplane.position:type_name -> wire.msg.FloatCoordinate
	4,  // 3: wire.msg.Island.army:type_name -> wire.msg.Army
	1,  // 4: wire.msg.Island.position:type_name -> wire.msg.Coordinate
	1,  // 5: wire.msg.Game.size:type_name -> wire.msg.Coordinate
	3,  // 6: wire.msg.Game.player_neutral:type_name -> wire.msg.Player
	3,  // 7: wire.msg.Game.players:type_name -> wire.msg.Player
	6,  // 8: wire.msg.Game.islands:type_name -> wire.msg.Island
	5,  // 9: wire.msg.Game.airplanes:type_name -> wire.msg.Airplane
	9,  // 10: wire.msg.EventEnvelope.event_game_start:type_name -> wire.msg.EventGameStart
	10, // 11: wire.msg.EventEnvelope.event_game_over:type_name -> wire.msg.EventGameOver
	11, // 12: wire.msg.EventEnvelope.event_game_tick:type_name -> wire.msg.EventGameTick
	7,  // 13: wire.msg.EventGameTick.game:type_name -> wire.msg.Game
	13, // 14: wire.msg.ActionEnvelope.action_game_leave:type_name -> wire.msg.ActionGameLeave
	14, // 15: wire.msg.ActionEnvelope.action_game_launch:type_name -> wire.msg.ActionGameLaunch
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_wire_msg_game_proto_init() }
func file_wire_msg_game_proto_init() {
	if File_wire_msg_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wire_msg_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatCoordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Army); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Airplane); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Island); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventGameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventGameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventGameTick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionGameLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wire_msg_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionGameLaunch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_wire_msg_game_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*EventEnvelope_EventGameStart)(nil),
		(*EventEnvelope_EventGameOver)(nil),
		(*EventEnvelope_EventGameTick)(nil),
	}
	file_wire_msg_game_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*ActionEnvelope_ActionGameLeave)(nil),
		(*ActionEnvelope_ActionGameLaunch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wire_msg_game_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_msg_game_proto_goTypes,
		DependencyIndexes: file_wire_msg_game_proto_depIdxs,
		EnumInfos:         file_wire_msg_game_proto_enumTypes,
		MessageInfos:      file_wire_msg_game_proto_msgTypes,
	}.Build()
	File_wire_msg_game_proto = out.File
	file_wire_msg_game_proto_rawDesc = nil
	file_wire_msg_game_proto_goTypes = nil
	file_wire_msg_game_proto_depIdxs = nil
}
